--B

SELECT CIRURGIAS.*, MEDICOS.nome, MEDICOS.crm 
FROM CIRURGIAS INNER JOIN MEDICOS ON CIRURGIAS.crm = MEDICOS.crm 
WHERE MONTH(CIRURGIAS.dataCir) = 10 and (CIRURGIAS.andar = 'D' and CIRURGIAS.numero = 14) 
ORDER BY MEDICOS.nome;