--query para o item a

SELECT MEDICOS.nome FROM MEDICOS, CIRURGIAS 
WHERE MEDICOS.crm = CIRURGIAS.crm AND MONTH(CIRURGIAS.dataCir) = MONTH(CIRURGIAS.dataCir)
GROUP BY CIRURGIAS.crm HAVING COUNT(CIRURGIAS.crm) > 30;

--query para o item b

SELECT CIRURGIAS.*, MEDICOS.nome, MEDICOS.crm 
FROM CIRURGIAS INNER JOIN MEDICOS ON CIRURGIAS.crm = MEDICOS.crm 
WHERE MONTH(CIRURGIAS.dataCir) = 10 AND (CIRURGIAS.andar = 'D' AND CIRURGIAS.numero = 14) 
ORDER BY MEDICOS.nome;

--query para o item c

SELECT CLIENTES.nome FROM CLIENTES, CIRURGIAS 
WHERE CLIENTES.cpf = CIRURGIAS.cpf AND YEAR(CLIENTES.dataNascCli) < 1953 AND CIRURGIAS.crm = 11011;

--query para o item d

SELECT MEDICOS.nome FROM MEDICOS, CIRURGIAS 
WHERE MEDICOS.crm = CIRURGIAS.crm AND MEDICOS.salario > 10000.00 AND MONTH(CIRURGIAS.dataCir) = 05 
GROUP BY CIRURGIAS.crm HAVING COUNT(CIRURGIAS.crm) = 45;